from collections import Counter
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from collections import defaultdict
from sklearn.feature_extraction.text import CountVectorizer
from math import log
from sklearn.feature_extraction.text import (
    TfidfVectorizer,
    HashingVectorizer
)
import pandas as pd

corpus = [
    "i love machine learning",
    "machine learning is amazing",
    "i love nlp",
    "nlp is a part of artificial intelligence",
    "deep learning powers modern ai"
]


def build_vocabulary(corpus):
    """
    Builds a vocabulary from the corpus.
    """
    vocabulary = {}
    index = 0
    for sentence in corpus:
        words = sentence.split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1
    return vocabulary


VOCABULARY = build_vocabulary(corpus)
def one_hot_encoding(word, vocabulary=VOCABULARY):
    """
    One Hot Encoding from scratch.
    """
    vector = [0] * len(vocabulary)
    if word in vocabulary:
        vector[vocabulary[word]] = 1
    return vector


def bag_of_words(sentence, vocabulary=VOCABULARY):
    """
    Bag of Words representation from scratch.
    """
    vector = [0] * len(vocabulary)
    words = sentence.split()
    for word in words:
        if word in vocabulary:
            vector[vocabulary[word]] += 1
    return vector


def build_document_term_matrix(corpus, vocabulary=VOCABULARY):
    """
    Builds the complete Document-Term Matrix.
    """
    matrix = []
    for sentence in corpus:
        matrix.append(
            bag_of_words(sentence, vocabulary)
        )
    return np.array(matrix)


def generate_ngrams(sentence, n):
    """
    Generates n-grams from a sentence.
    """
    words = sentence.split()
    ngrams = []
    for i in range(len(words) - n + 1):
        ngrams.append(
            tuple(words[i:i + n])
        )
    return ngrams


def count_vectorizer(corpus):
    """
    Count Vectorizer using Scikit-Learn.
    """
    vectorizer = CountVectorizer()
    matrix = vectorizer.fit_transform(corpus)
    return (
        vectorizer.get_feature_names_out(),
        matrix.toarray()
    )


def term_frequency(sentence):
    """
    Calculates Term Frequency (TF).
    """
    words = sentence.split()
    total_words = len(words)
    word_counts = Counter(words)
    tf = {}
    for word, count in word_counts.items():
        tf[word] = count / total_words
    return tf


def inverse_document_frequency(corpus):
    """
    Calculates Inverse Document Frequency (IDF).
    """
    N = len(corpus)
    idf = {}
    vocabulary = set()
    for sentence in corpus:
        vocabulary.update(sentence.split())
    for word in vocabulary:
        document_frequency = 0
        for sentence in corpus:
            if word in sentence.split():
                document_frequency += 1
        idf[word] = log(N / (document_frequency + 1)) + 1
    return idf


def tfidf_from_scratch(corpus):
    """
    Computes TF-IDF from scratch.
    """
    idf = inverse_document_frequency(corpus)
    tfidf_matrix = []
    for sentence in corpus:
        tf = term_frequency(sentence)
        vector = []
        for word in VOCABULARY:
            vector.append(
                tf.get(word, 0) * idf[word]
            )
        tfidf_matrix.append(vector)
    return np.array(tfidf_matrix)


def tfidf_vectorizer(corpus):
    """
    TF-IDF using Scikit-Learn.
    """
    vectorizer = TfidfVectorizer()
    matrix = vectorizer.fit_transform(corpus)
    return (
        vectorizer.get_feature_names_out(),
        matrix.toarray()
    )


def hashing_vectorizer(corpus):
    """
    Hashing Vectorizer using Scikit-Learn.
    """
    vectorizer = HashingVectorizer(
        n_features=10,
        alternate_sign=False
    )
    matrix = vectorizer.transform(corpus)
    return matrix.toarray()


def show_sparse_matrix(corpus):
    """
    Returns the sparse matrix generated by CountVectorizer.
    """

    vectorizer = CountVectorizer()

    matrix = vectorizer.fit_transform(corpus)

    return matrix


def show_dense_matrix(corpus):
    """
    Converts sparse matrix to dense matrix.
    """

    vectorizer = CountVectorizer()

    matrix = vectorizer.fit_transform(corpus)

    return matrix.toarray()


def compare_methods(corpus):
    """
    Compare different text representation techniques.
    """
    print("=" * 60)
    print("COMPARISON OF TEXT REPRESENTATION METHODS")
    print("=" * 60)
    print()
    print("Vocabulary Size :", len(VOCABULARY))
    print()
    print("Bag of Words Shape :")
    print(build_document_term_matrix(corpus).shape)
    print()
    words, count_matrix = count_vectorizer(corpus)
    print("Count Vectorizer Shape :")
    print(count_matrix.shape)
    print()
    words, tfidf_matrix = tfidf_vectorizer(corpus)
    print("TF-IDF Shape :")
    print(tfidf_matrix.shape)
    print()
    hash_matrix = hashing_vectorizer(corpus)
    print("Hashing Vectorizer Shape :")
    print(hash_matrix.shape)
    print()
    comparison = pd.DataFrame({
        "Technique": [
            "One Hot Encoding",
            "Bag of Words",
            "Count Vectorizer",
            "TF-IDF",
            "Hashing Vectorizer"
        ],
        "Uses Vocabulary": [
            "Yes",
            "Yes",
            "Yes",
            "Yes",
            "No"
        ],
        "Captures Frequency": [
            "No",
            "Yes",
            "Yes",
            "Yes",
            "Yes"
        ],
        "Captures Importance": [
            "No",
            "No",
            "No",
            "Yes",
            "No"
        ]
    })
    print(comparison)


if __name__ == "__main__":

    print("=" * 60)
    print("VOCABULARY")
    print("=" * 60)

    print(VOCABULARY)

    print()

    print("=" * 60)
    print("ONE HOT ENCODING")
    print("=" * 60)

    print(one_hot_encoding("learning"))

    print()

    print("=" * 60)
    print("BAG OF WORDS")
    print("=" * 60)

    sentence = "i love learning"

    print(sentence)

    print()

    print(bag_of_words(sentence))

    print()

    print("=" * 60)
    print("DOCUMENT TERM MATRIX")
    print("=" * 60)

    matrix = build_document_term_matrix(corpus)

    print(matrix)

    print("=" * 60)
    print("UNIGRAMS")
    print("=" * 60)

    print(generate_ngrams("i love machine learning", 1))

    print()

    print("=" * 60)
    print("BIGRAMS")
    print("=" * 60)

    print(generate_ngrams("i love machine learning", 2))

    print()

    print("=" * 60)
    print("TRIGRAMS")
    print("=" * 60)

    print(generate_ngrams("i love machine learning", 3))

    print()

    print("=" * 60)
    print("COUNT VECTORIZER")
    print("=" * 60)

    words, matrix = count_vectorizer(corpus)

    print(words)

    print()

    print(matrix)

    print()

    print("=" * 60)
    print("TERM FREQUENCY")
    print("=" * 60)

    tf = term_frequency("i love machine learning machine")

    print(tf)

    print()

    print("=" * 60)
    print("INVERSE DOCUMENT FREQUENCY")
    print("=" * 60)

    idf = inverse_document_frequency(corpus)
    for word, value in idf.items():
        print(f"{word:15} {value:.4f}")

    print("=" * 60)
    print("TF-IDF FROM SCRATCH")
    print("=" * 60)

    tfidf = tfidf_from_scratch(corpus)

    print(tfidf)

    print()

    print("=" * 60)
    print("TF-IDF VECTORIZER")
    print("=" * 60)

    words, matrix = tfidf_vectorizer(corpus)

    print(words)

    print()

    print(matrix)

    print()

    print("=" * 60)
    print("HASHING VECTORIZER")
    print("=" * 60)

    print(hashing_vectorizer(corpus))

    print("=" * 60)
    print("SPARSE MATRIX")
    print("=" * 60)

    sparse = show_sparse_matrix(corpus)

    print(sparse)

    print()

    print("=" * 60)
    print("DENSE MATRIX")
    print("=" * 60)

    dense = show_dense_matrix(corpus)

    print(dense)

    print()

    compare_methods(corpus)